require 'fileutils'

task :default => ["kandi:build"]
task :clean => %w[kandi:clean]
namespace :kandi do
  desc "Build kandi.tex with ../lahteet.bib"
  task :build do
    sh "cd kandi && pdflatex kandi && bibtex kandi && pdflatex kandi && pdflatex kandi"
  end

  desc "Cleans crap generated by latex from kandi folder"
  task :clean do
    crap = %w[kandi.aux kandi.bbl kandi.blg kandi.log kandi.out kandi.pdf]
    FileUtils.chdir "kandi" do
      FileUtils.rm_rf crap
    end
  end
end

